var pizzeRegioni=[
	{
		nome : "Lardellata",
		regione : "Toscana",
		ingredienti :["pomodoro","mozzarella","lardo di Colonnata","ciliegini","porcini"],
		minX : 134,
		minY : 128,
		maxX : 202,
		maxY : 222,
		prezzo : 10,
		carboidrati : 15,
		grassi : 113,
		proteine : 34,


	},
	{
		nome : "Senese",
		regione : "Toscana",
		ingredienti :["pomodoro","mozzarella","crudo di cinta senese","porcini"],
		minX : 134,
		minY : 128,
		maxX : 202,
		maxY : 222,
		prezzo : 10,
		carboidrati : 12,
		grassi : 24,
		proteine : 52,

	},
	{
		nome : "Tartufo",
		regione : "Toscana",
		ingredienti :["pomodoro","mozzarella","tartufo nero"],
		minX : 134,
		minY : 128,
		maxX : 202,
		maxY : 222,
		prezzo : 9,
		carboidrati : 8,
		grassi : 19,
		proteine : 35,


	},
	{
		nome : "Parma",
		regione : "Emilia-Romagna",
		ingredienti : ["pomodoro", "mozzarella","prosciutto crudo di Parma"],
		minX : 98,
		minY : 74,
		maxX : 218,
		maxY : 117,
		prezzo : 6.50,
		carboidrati : 8,
		grassi : 24,
		proteine : 50,

	},
	{
		nome : "Romagnola",
		regione : "Emilia-Romagna",
		ingredienti : ["pomodoro", "mozzarella","parmigiano reggiano","ciliegini","aceto di Modena"],
		minX : 98,
		minY : 74,
		maxX : 218,
		maxY : 117,
		prezzo : 6,
		carboidrati : 15,
		grassi : 48,
		proteine : 68,

	},
	{
		nome : "Borso",
		regione : "Veneto",
		ingredienti : ["pomodoro","mozzarella","piselli di Borso","rucola","radicchio rosso"],
		minX : 167,
		minY : 16,
		maxX : 233,
		maxY : 65,
		prezzo : 6,
		carboidrati : 32,
		grassi : 19,
		proteine : 39,

	},
	{
		nome : "Castrozza",
		regione : "Veneto",
		ingredienti : ["pomodoro","mozzarella","fungo castrozza","rucola"],
		minX : 167,
		minY : 16,
		maxX : 233,
		maxY : 65,
		prezzo : 7,
		carboidrati : 16,
		grassi : 19,
		proteine : 34,

	},
	{
		nome : "Friulana",
		regione : "Friuli",
		ingredienti :["pomodoro","mozzarella","prosciutto di San Daniele","ciliegini","radicchio rosso"],
		minX : 247,
		minY : 0,
		maxX : 292,
		maxY : 20,
		prezzo : 8,
		carboidrati : 17,
		grassi : 25,
		proteine : 53,

	},
	{
		nome : "Asiago",
		regione : "Trentino",
		ingredienti : ["pomodoro","mozzarella","asiago"],
		minX : 150,
		minY : 0,
		maxX : 198,
		maxY : 17,
		prezzo : 6,
		carboidrati : 11,
		grassi : 47,
		proteine : 67,

	},
	{
		nome : "SeM",
		regione : "Trentino",
		ingredienti : ["pomodoro","mozzarella","speck","Mascarpone"],
		minX : 150,
		minY : 0,
		maxX : 198,
		maxY : 17,
		prezzo : 6.50,
		carboidrati : 8,
		grassi : 85,
		proteine : 67,
	},
	{
		nome : "Bresaola",
		regione : "Lombardia",
		ingredienti :["pomodoro","mozzarella","bresaola della Valtellina"],
		minX : 70,
		minY : 0,
		maxX : 141,
		maxY : 51,
		prezzo : 7.50,
		carboidrati : 7,
		grassi : 21,
		proteine : 61,

	},
	{
		nome : "Lombarda",
		regione : "Lombardia",
		ingredienti :["mozzarella","gorgonzola","grana padano"],
		minX : 70,
		minY : 0,
		maxX : 141,
		maxY : 51,
		prezzo : 6.50,
		carboidrati : 9,
		grassi : 75,
		proteine : 87,
	},
	{
		nome : "Carmagnola",
		regione : "Piemonte",
		ingredienti : ["pomodoro","mozzarella","tomino","peperone di Carmagnola"],
		minX : 0,
		minY : 22,
		maxX : 70,
		maxY : 81,
		prezzo : 7,
		carboidrati : 25,
		grassi : 50,
		proteine : 65,

	},
	{
		nome : "Doja",
		regione : "Piemonte",
		ingredienti : ["pomodoro","mozzarella","tomino","salsiccia doja"],
		minX : 0,
		minY : 22,
		maxX : 70,
		maxY : 81,
		prezzo : 7.50,
		carboidrati : 15,
		grassi : 77,
		proteine : 81,

	},
	{
		nome : "Jambon",
		regione : "Valle D'Aosta",
		ingredienti :["pomodoro","mozzarella","rucola","fontina","prosciutto crudo Jambon De Bosses"],
		minX : 0,
		minY : 0,
		maxX : 25,
		maxY : 10,
		prezzo : 9,
		carboidrati : 16,
		grassi : 54,
		proteine : 90,

	},
	{
		nome : "Liguriana",
		regione : "Liguria",
		ingredienti :["pomodoro","mozzarella","pomodoro cuore di bue","asparago violetto di Albenga"],
		minX : 3,
		minY : 87,
		maxX : 112,
		maxY : 106,
		prezzo : 7,
		carboidrati : 15,
		grassi : 20,
		proteine : 32,

	},
	{
		nome : "Colfiorito",
		regione : "Umbria",
		ingredienti : ["pomodoro","mozzarella","ciliegini","patate rosse di Colfiorito"],
		minX : 202,
		minY : 169,
		maxX : 237,
		maxY : 227,
		prezzo : 6,
		carboidrati : 28,
		grassi : 19,
		proteine : 32,

	},
	{
		nome : "Norcia",
		regione : "Umbria",
		ingredienti : ["pomodoro","mozzarella","tartufo nero di Norcia","pecorino di Norcia"],
		minX : 202,
		minY : 169,
		maxX : 237,
		maxY : 227,
		prezzo : 12,
		carboidrati : 11,
		grassi : 48,
		proteine : 73,

	},
	{
		nome : "Marchigiana",
		regione : "Marche",
		ingredienti : ["pomodoro","salsiccia","condimento di sepa"],
		minX : 245,
		minY : 149,
		maxX : 278,
		maxY : 208,
		prezzo : 6.50,
		carboidrati : 7,
		grassi : 30,
		proteine : 15,

	},
	{
		nome : "Carbonara",
		regione : "Lazio",
		ingredienti :["mozzarella","guanciale","uovo","pecorino romano"],
		minX : 207,
		minY : 220,
		maxX : 237,
		maxY : 305,
		prezzo : 10,
		carboidrati : 8,
		grassi : 126,
		proteine : 86,

	},
	{
		nome : "Romanesca",
		regione : "Lazio",
		ingredienti :["pomodoro","mozzarella","carciofo romanesco"],
		minX : 207,
		minY : 220,
		maxX : 237,
		maxY : 305,
		prezzo : 7,
		carboidrati : 18,
		grassi : 19,
		proteine : 32,

	},
	{
		nome : "Abruzzese",
		regione : "Abruzzo",
		ingredienti : ["pomodoro","mozzarella","scamorza abruzzese"],
		minX : 260,
		minY : 224,
		maxX : 300,
		maxY : 271,
		prezzo : 6.50,
		carboidrati : 7,
		grassi : 43,
		proteine : 54,

	},
	{
		nome : "Zafferano",
		regione : "Abruzzo",
		ingredienti : ["mozzarella","zafferano"],
		minX : 260,
		minY : 224,
		maxX : 300,
		maxY : 271,
		prezzo : 7.50,
		carboidrati : 68,
		grassi : 23,
		proteine : 39,

	},
	{
		nome : "Isernia",
		regione : "Molise",
		ingredienti :["pomodoro","cipolla di Isernia"],
		minX : 292,
		minY : 274,
		maxX : 333,
		maxY : 299,
		prezzo : 6,
		carboidrati : 30,
		grassi : 5,
		proteine : 5,

	},
	{
		nome : "Molisiana",
		regione : "Molise",
		ingredienti :["pomodoro","mozzarella","peperone verde"],
		minX : 292,
		minY : 274,
		maxX : 333,
		maxY : 299,
		prezzo : 6,
		carboidrati : 13,
		grassi : 19,
		proteine : 30,

	},
	{
		nome : "Bufalina",
		regione : "Campania",
		ingredienti :["pomodoro", "mozzarella","mozzarella di bufala", "ciliegini"],
		minX : 309,
		minY : 304,
		maxX : 343,
		maxY : 388,
		prezzo : 8,
		carboidrati : 15,
		grassi : 43,
		proteine : 46,

	},
	{
		nome : "Paestum",
		regione : "Campania",
		ingredienti :["pomodoro", "mozzarella","mozzarella di bufala", "carciofo paestum","pomodorino di San Marzano"],
		minX : 309,
		minY : 304,
		maxX : 343,
		maxY : 388,
		prezzo : 12,
		carboidrati : 25,
		grassi : 44,
		proteine : 50,

	},
	{
		nome : "Cucumbarazzu",
		regione : "Puglia",
		ingredienti : ["pomodoro","mozzarella","zucchine cucumbarazzu","scamorza di pecora"],
		minX : 370,
		minY : 272,
		maxX : 460,
		maxY : 340,
		prezzo : 8,
		carboidrati : 10,
		grassi : 45,
		proteine : 55,

	},
	{
		nome : "Basilicata",
		regione : "Basilicata",
		ingredienti : ["pomodoro", "cipolla iampascioni", "caciocavallo"],
		minX : 370,
		minY : 335,
		maxX : 405,
		maxY : 385,
		prezzo : 7.50,
		carboidrati :15,
		grassi : 35,
		proteine : 40,

	},
	{
		nome : "Sarcona",
		regione : "Basilicata",
		ingredienti : ["pomodoro", "mozzarella", "fagioli sarconi"],
		minX : 370,
		minY : 335,
		maxX : 405,
		maxY : 385,
		prezzo : 6,
		carboidrati : 67,
		grassi : 20,
		proteine : 55,

	},
	{
		nome : "Formaggi",
		regione : "Calabria",
		ingredienti : ["mozzarella","formaggio giuncata", "ricotta affumicata"],
		minX : 378,
		minY : 400,
		maxX : 428,
		maxY : 523,
		prezzo : 7.50,
		carboidrati : 15,
		grassi : 54,
		proteine : 78,

	},
	{
		nome : "Nduja",
		regione : "Calabria",
		ingredienti : ["pomodoro", "mozzarella","nduja"],
		minX : 378,
		minY : 400,
		maxX : 428,
		maxY : 523,
		prezzo : 8,
		carboidrati : 10,
		grassi : 25,
		proteine : 30,

	},
	{
		nome : "Tropea",
		regione : "Calabria",
		ingredienti : ["pomodoro", "mozzarella","cipolla di Tropea"],
		minX : 378,
		minY : 400,
		maxX : 428,
		maxY : 523,
		prezzo : 7,
		carboidrati : 20,
		grassi : 15,
		proteine : 30,

	},
	{
		nome : "Pleurotus",
		regione : "Sicilia",
		ingredienti :["pomodoro","mozzarella","fungo pleurotus"],
		minX : 198,
		minY : 507,
		maxX : 349,
		maxY : 608,
		prezzo : 7,
		carboidrati : 20,
		grassi : 18,
		proteine : 30,

	},
	{
		nome : "Sicula",
		regione : "Sicilia",
		ingredienti :["pomodoro","mozzarella","olive nere piccanti","pomodoro pachino"],
		minX : 198,
		minY : 507,
		maxX : 349,
		maxY : 608,
		prezzo : 6.50,
		carboidrati : 10,
		grassi : 45,
		proteine : 30,

	},
	{
		nome : "Marittima",
		regione : "Sardegna",
		ingredienti : ["pomodoro","mozzarella","gamberetti","totani"],
		minX : 0,
		minY : 307,
		maxX : 80,
		maxY : 447,
		prezzo : 12,
		carboidrati : 10,
		grassi : 20,
		proteine : 58,

	},
	{
		nome : "Sarda",
		regione : "Sardegna",
		ingredienti : ["pomodoro","mozzarella","ciliegini","pecorino sardo"],
		minX : 0,
		minY : 307,
		maxX : 80,
		maxY : 447,
		prezzo : 7,
		carboidrati : 25,
		grassi : 55,
		proteine : 67,

	},
];
var ingredienti = [
	{
		tipo : "base",
		nome : "Pomodoro",
	},
	{
		tipo : "base",
		nome : "Mozzarella",
	},
	{
		tipo : "formaggio",
		nome : "Grana",
	},
	{
		tipo : "formaggio",
		nome : "Mascarpone",
	},
	{
		tipo : "formaggio",
		nome : "Scamorza",
	},
		{
		tipo : "formaggio",
		nome : "Bufala",
	},
	{
		tipo : "verdura",
		nome : "Ciliegini",
	},
	{
		tipo : "verdura",
		nome : "Funghi",
	},
	{
		tipo : "verdura",
		nome : "Rucola",
	},
	{
		tipo : "verdura",
		nome : "Peperone",
	},
	{
		tipo : "verdura",
		nome : "Zucchine",	},
		{
		tipo : "verdura",
		nome : "Cipolla",
	},
	{
		tipo : "carne",
		nome : "Crudo",
	},
	{
		tipo : "carne",
		nome : "Cotto",
	},
	{
		tipo : "carne",
		nome : "Speck",
	},
	{
		tipo : "carne",
		nome : "Salsiccia",
	},
	{
		tipo : "mare",
		nome : "Gamberetti",
	},
		{
		tipo : "mare",
		nome : "Totani",
	},
]